project_name: kubenow

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: kubenow
    main: ./cmd/kubenow
    binary: kubenow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: kubenow-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactors
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: ppiankov
    name: kubenow
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## kubenow {{ .Tag }} ({{ .Date }})

    ### Installation

    Download the appropriate binary for your platform:

    ```bash
    # Linux amd64
    curl -LO https://github.com/ppiankov/kubenow/releases/download/{{ .Tag }}/kubenow_{{ .Version }}_linux_amd64.tar.gz
    tar -xzf kubenow_{{ .Version }}_linux_amd64.tar.gz
    sudo mv kubenow /usr/local/bin/

    # macOS amd64
    curl -LO https://github.com/ppiankov/kubenow/releases/download/{{ .Tag }}/kubenow_{{ .Version }}_darwin_amd64.tar.gz
    tar -xzf kubenow_{{ .Version }}_darwin_amd64.tar.gz
    sudo mv kubenow /usr/local/bin/

    # macOS arm64 (Apple Silicon)
    curl -LO https://github.com/ppiankov/kubenow/releases/download/{{ .Tag }}/kubenow_{{ .Version }}_darwin_arm64.tar.gz
    tar -xzf kubenow_{{ .Version }}_darwin_arm64.tar.gz
    sudo mv kubenow /usr/local/bin/
    ```

    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/ppiankov/kubenow/compare/{{ .PreviousTag }}...{{ .Tag }}
