// Package telemetry provides an opt-in Prometheus metrics endpoint for kubenow self-monitoring.
package telemetry

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// Metrics holds all kubenow telemetry counters and histograms.
type Metrics struct {
	QueryDuration    *prometheus.HistogramVec
	QueryErrors      *prometheus.CounterVec
	QueriesTotal     *prometheus.CounterVec
	AnalysisDuration *prometheus.HistogramVec
	Recommendations  *prometheus.CounterVec
}

// NewMetrics creates and registers all kubenow metrics.
func NewMetrics(reg prometheus.Registerer) *Metrics {
	m := &Metrics{
		QueryDuration: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Name:    "kubenow_query_duration_seconds",
			Help:    "Duration of Prometheus queries in seconds.",
			Buckets: prometheus.DefBuckets,
		}, []string{"type"}),
		QueryErrors: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "kubenow_query_errors_total",
			Help: "Total number of failed Prometheus queries.",
		}, []string{"type"}),
		QueriesTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "kubenow_queries_total",
			Help: "Total number of Prometheus queries executed.",
		}, []string{"type"}),
		AnalysisDuration: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Name:    "kubenow_analysis_duration_seconds",
			Help:    "Duration of analysis runs in seconds.",
			Buckets: []float64{1, 5, 10, 30, 60, 120, 300},
		}, []string{"command"}),
		Recommendations: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "kubenow_recommendations_total",
			Help: "Total recommendations generated by outcome.",
		}, []string{"outcome"}),
	}

	reg.MustRegister(m.QueryDuration, m.QueryErrors, m.QueriesTotal, m.AnalysisDuration, m.Recommendations)
	return m
}

// RecordQuery records a query execution.
func (m *Metrics) RecordQuery(queryType string, duration time.Duration, err error) {
	m.QueriesTotal.WithLabelValues(queryType).Inc()
	m.QueryDuration.WithLabelValues(queryType).Observe(duration.Seconds())
	if err != nil {
		m.QueryErrors.WithLabelValues(queryType).Inc()
	}
}

// RecordAnalysis records an analysis run duration.
func (m *Metrics) RecordAnalysis(command string, duration time.Duration) {
	m.AnalysisDuration.WithLabelValues(command).Observe(duration.Seconds())
}

// Server serves the /metrics endpoint.
type Server struct {
	httpServer *http.Server
	metrics    *Metrics
}

// NewServer creates a metrics server on the given port.
func NewServer(port int) *Server {
	reg := prometheus.NewRegistry()
	reg.MustRegister(collectors.NewGoCollector())
	m := NewMetrics(reg)

	mux := http.NewServeMux()
	mux.Handle("/metrics", promhttp.HandlerFor(reg, promhttp.HandlerOpts{}))

	return &Server{
		httpServer: &http.Server{
			Addr:              fmt.Sprintf(":%d", port),
			Handler:           mux,
			ReadHeaderTimeout: 10 * time.Second,
		},
		metrics: m,
	}
}

// Metrics returns the metrics instance for recording.
func (s *Server) Metrics() *Metrics {
	return s.metrics
}

// Start begins serving metrics. Blocks until context is canceled.
func (s *Server) Start(ctx context.Context) error {
	go func() {
		<-ctx.Done()
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		//nolint:errcheck // best-effort shutdown on context cancellation
		s.httpServer.Shutdown(shutdownCtx)
	}()

	if err := s.httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		return fmt.Errorf("metrics server failed: %w", err)
	}
	return nil
}
