package export

import (
	"fmt"
	"io"
)

// exportHTML exports the result as HTML (Phase 2 - placeholder for now).
func exportHTML(result interface{}, metadata ExportMetadata, w io.Writer) error {
	// TODO: Implement beautiful HTML export in Phase 2
	// For now, return a simple HTML wrapper with JSON
	html := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
    <title>kubenow Report - %s - %s</title>
    <meta charset="UTF-8">
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 1200px; margin: 40px auto; padding: 20px; }
        h1 { color: #1976d2; }
        .metadata { background: #f5f5f5; padding: 15px; border-left: 4px solid #1976d2; margin-bottom: 20px; }
        pre { background: #f5f5f5; padding: 15px; overflow-x: auto; }
    </style>
</head>
<body>
    <h1>kubenow Report</h1>
    <div class="metadata">
        <p><strong>Generated:</strong> %s</p>
        <p><strong>Cluster:</strong> %s</p>
        <p><strong>Mode:</strong> %s</p>
        <p><strong>Version:</strong> %s</p>
    </div>
    <h2>Result</h2>
    <pre>%v</pre>
    <hr>
    <p><em>Generated by <a href="https://github.com/ppiankov/kubenow">kubenow</a></em></p>
</body>
</html>`,
		metadata.Mode,
		metadata.GeneratedAt.Format("2006-01-02"),
		metadata.GeneratedAt.Format("2006-01-02 15:04:05 UTC"),
		metadata.ClusterName,
		metadata.Mode,
		metadata.KubenowVersion,
		result,
	)

	_, err := w.Write([]byte(html))
	return err
}
